import { useEffect, useState, type FormEvent } from "react";
import { Check, ClipboardList, LoaderCircle } from "lucide-react";
import type { Translate } from "../i18n";
import { DockerMountPicker } from "./DockerMountPicker";
import { OperationFailureNotice } from "./OperationFailureNotice";
import { newRunId } from "../shared/run-id";
import { cancelJob, hasTauriRuntime, listRepositories, listSshProfiles, runCapturePlan, saveCapturePlan, type RepositorySummary, type SshProfileSummary } from "../shared/commands";

export function CapturePlanPanel({ resourcesRevision, t }: { resourcesRevision: number; t: Translate }) {
  const [profiles, setProfiles] = useState<SshProfileSummary[]>([]); const [repositories, setRepositories] = useState<RepositorySummary[]>([]);
  const [profileId, setProfileId] = useState(""); const [repositoryId, setRepositoryId] = useState(""); const [roots, setRoots] = useState("/srv/app"); const [databasePath, setDatabasePath] = useState(""); const [working, setWorking] = useState(false); const [running, setRunning] = useState(false); const [runId, setRunId] = useState<string>(); const [planId, setPlanId] = useState<string>(); const [result, setResult] = useState<string>(); const [failure, setFailure] = useState<string>();
  const addRootPath = (path: string) => { setRoots((current) => (current.trim() ? `${current}\n${path}` : path)); };
  useEffect(() => { void Promise.all([listSshProfiles(), listRepositories()]).then(([nextProfiles, nextRepositories]) => { const readyRepositories = nextRepositories.filter((item) => item.recoveryReady); setProfiles(nextProfiles); setRepositories(readyRepositories); setProfileId(nextProfiles[0]?.profileId ?? ""); setRepositoryId(readyRepositories[0]?.repositoryId ?? ""); }); }, [resourcesRevision]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!hasTauriRuntime()) return; setWorking(true); setFailure(undefined); try { const plan = await saveCapturePlan({ profileId, repositoryId, roots: roots.split("\n").map((root) => root.trim()).filter(Boolean), databasePath: databasePath.trim() || undefined }); setPlanId(plan.planId); setResult(`План сохранён: ${plan.roots.join(", ")}${plan.databasePath ? ` + ${plan.databasePath}` : ""}`); } catch { setFailure("Не удалось сохранить план. Проверьте сервер, хранилище и абсолютные пути."); } finally { setWorking(false); } };
  const run = async () => { if (!planId) return; const nextRunId = newRunId(); setRunId(nextRunId); setRunning(true); setFailure(undefined); try { const job = await runCapturePlan(planId, nextRunId); setResult(`Бэкап sealed: ${job.backupId}`); } catch { setFailure("Бэкап не прошёл проверенный lifecycle, или был отменён. Проверьте signing identity, SSH и свободное место."); } finally { setRunning(false); setRunId(undefined); } };
  const cancel = async () => { if (!runId) return; await cancelJob(runId); };
  return <section className="repository-panel" aria-labelledby="plan-title"><header className="repository-panel__header"><div><p className="eyebrow"><ClipboardList size={15} />План</p><h2 id="plan-title">Что сохраняем</h2><p>Выберите сервер, хранилище и папки на VDS. Каждая строка — одна абсолютная папка.</p></div></header><form className="repository-form" onSubmit={(event) => void submit(event)}><label><span>Сервер</span><select value={profileId} onChange={(event) => setProfileId(event.target.value)} required>{profiles.map((profile) => <option key={profile.profileId} value={profile.profileId}>{profile.label}</option>)}</select></label><label><span>Хранилище</span><select value={repositoryId} onChange={(event) => setRepositoryId(event.target.value)} required>{repositories.map((repository) => <option key={repository.repositoryId} value={repository.repositoryId}>{repository.label}</option>)}</select></label><label className="repository-form__actions"><span>Папки VDS</span><textarea value={roots} onChange={(event) => setRoots(event.target.value)} required /></label><DockerMountPicker profileId={profileId} onAddPath={addRootPath} /><label className="repository-form__actions"><span>Файл базы данных на сервере (необязательно)</span><input value={databasePath} onChange={(event) => setDatabasePath(event.target.value)} placeholder="/srv/app/app.sqlite" /></label><div className="repository-form__actions"><button className="button button--primary" disabled={!profileId || !repositoryId || working || running} type="submit">{working ? <LoaderCircle className="spin" size={16} /> : <Check size={16} />}{working ? "Сохраняем…" : "Сохранить план"}</button>{planId && <button className="button button--secondary" disabled={working || running} type="button" onClick={() => void run()}>{running ? <LoaderCircle className="spin" size={16} /> : <Check size={16} />}{running ? "Проверяем и сохраняем…" : "Запустить бэкап"}</button>}{running && <button className="button button--secondary" type="button" onClick={() => void cancel()}>Отменить</button>}</div></form>{result && <p className="repository-panel__success"><Check size={16} />{result}</p>}{failure && <OperationFailureNotice message={failure} safe="captureFailureSafe" changed="captureFailureChanged" t={t} />}</section>;
}
